config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('exam.urls')),
]

urlpatterns += static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

exam/urls.py
from django.urls import path
from .views import PostDetailView, post_list,post_search,AboutView,ContactView

app_name = 'exam'

urlpatterns = [

    path('', post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', post_list, name='post_list_by_tag'),
    path('post/<int:year>/<int:month>/<int:day>/<slug:slug>/', PostDetailView.as_view(), name='post_detail'),
    path('search/', post_search, name='post_search'),
    path('about/', AboutView.as_view(), name='about'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('category/<int:category_id>/', post_list, name='post_by_category'),

]


templates/about.html
{% extends "base.html" %}
{% block content %}
{% load static %}


<section class="section-sm">
	<div class="container">
		<div class="row">
			<div class="col-12">
				<div class="title-bordered mb-5 d-flex align-items-center">
					<h1 class="h4">Hi, I Am John Doe</h1>
					<ul class="list-inline social-icons ml-auto mr-3 d-none d-sm-block">
						<li class="list-inline-item"><a href="#"><i class="ti-facebook"></i></a>
						</li>
						<li class="list-inline-item"><a href="#"><i class="ti-twitter-alt"></i></a>
						</li>
						<li class="list-inline-item"><a href="#"><i class="ti-linkedin"></i></a>
						</li>
						<li class="list-inline-item"><a href="#"><i class="ti-github"></i></a>
						</li>
					</ul>
				</div>
				<img src="{% static 'images/author-full.jpg' %}" class="img-fluid w-100 mb-4 rounded-lg" alt="author">
				<div class="content">
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Condimentum in urna justo elit turpis risus vitae viverra enim. Augue quis vitae in non nisi, posuere ultrices tempus. Feugiat consequat suspendisse laoreet vitae enim adipiscing cursus. Duis nunc vitae tincidunt sed nibh id. Egestas erat consequat, ornare etiam donec faucibus. Lorem ut enim nunc, senectus adipiscing sed. Lobortis commodo aliquet pulvinar molestie faucibus diam. Semper porttitor justo, et dictum</p>
					<p>Faucibus duis urna, consequat morbi imperdiet pulvinar. Mauris vitae sed aliquet eu tincidunt id. Nulla leo eget erat vel pharetra. Morbi nullam morbi non purus, augue. Massa cras odio ante cursus a mauris. Volutpat faucibus feugiat feugiat euismod congue ridiculus. Et ipsum euismod nulla et aenean diam duis. Sem molestie est mauris sit. Et eleifend odio</p>
					<div class="quote"> <i class="ti-quote-left"></i>
						<div>
							<p>Life is a series of natural and spontaneous changes. Don’t resist them – that only create sorrow. Let reality changes be reality. Let things flow naturally way they like.</p> <span class="quote-by"> -John Doe</span>
						</div>
					</div>
					<hr>
					<h4 id="my-skills--experiences">My Skills &amp; Experiences:</h4>
					<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cumto sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec.</p>
					<ul>
						<li>In enim justo, rhoncus ut,</li>
						<li>Curabitur ullamcorper ultricies</li>
						<li>Donec vitae sapien utlorem</li>
					</ul>
					<p>Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna.</p>
				</div>
			</div>
		</div>
	</div>
</section>



 {% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
{% load blog_tags %}

<html lang="en-us">
<head>
   <meta charset="utf-8">
   <title>Logbook - Homepage List</title>

   <!-- mobile responsive meta -->
   <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=5">
   <meta name="description" content="This is meta description">
   <meta name="author" content="Astrum">
   <!-- plugins -->
   <link rel="preload" href="https://fonts.gstatic.com/s/opensans/v18/mem8YaGs126MiZpBA-UFWJ0bbck.woff2" style="font-display: optional;">
   <link rel="stylesheet" href="{% static 'plugins/bootstrap/bootstrap.min.css' %}">
   <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:600%7cOpen&#43;Sans&amp;display=swap" media="screen">

   <link rel="stylesheet" href="{% static 'plugins/themify-icons/themify-icons.css' %}">
   <link rel="stylesheet" href="{% static 'plugins/slick/slick.css' %}">

   <!-- Main Stylesheet -->
   <link rel="stylesheet" href="{% static 'css/style.css' %}">

   <!--Favicon-->
   <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="image/x-icon">
   <link rel="icon" href="{% static 'images/favicon.png' %}" type="image/x-icon">
</head>

<body>
<header class="sticky-top bg-white border-bottom border-default">
   <div class="container">

      <nav class="navbar navbar-expand-lg navbar-white">
         <a class="navbar-brand" href="{% url 'exam:post_list' %}">
            <img class="img-fluid" width="150px" src="{% static 'images/logo.png' %}" alt="LogBook">
         </a>
         <button class="navbar-toggler border-0" type="button" data-toggle="collapse" data-target="#navigation">
            <i class="ti-menu"></i>
         </button>

         <div class="collapse navbar-collapse text-center" id="navigation">
            <ul class="navbar-nav ml-auto">
               <li class="nav-item">
                  <a class="nav-link" href="{% url 'exam:post_list' %}">Home</a>
               </li>
               <li class="nav-item">
                  <a class="nav-link" href="{% url 'exam:about' %}">About</a>
               </li>
               <li class="nav-item">
                  <a class="nav-link" href="{% url 'exam:contact' %}">Contact</a>
               </li>
            </ul>

            <!-- search -->
            <div class="search px-4">
               <button id="searchOpen" class="search-btn"><i class="ti-search"></i></button>
               <div class="search-wrapper">
                  <form action="{% url 'exam:post_search' %}" class="h-100">
                     <input class="search-box pl-4" id="search-query" name="query" type="search" placeholder="Type &amp; Hit Enter...">
                  </form>
                  <button id="searchClose" class="search-close"><i class="ti-close text-dark"></i></button>
               </div>
            </div>

         </div>
      </nav>
   </div>
</header>

    {% block content %}

    {% endblock %}

<footer class="section-sm pb-0 border-top border-default">
      <div class="container">
         <div class="row justify-content-between">
            <div class="col-md-3 mb-4">
               <a class="mb-4 d-block" href="index.html">
                  <img class="img-fluid" width="150px" src="{% static 'images/logo.png' %}" alt="LogBook">
               </a>
               <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</p>
            </div>

            <div class="col-lg-2 col-md-3 col-6 mb-4">
               <h6 class="mb-4">Quick Links</h6>
               <ul class="list-unstyled footer-list">
                  <li><a href="/about">About</a></li>
                  <li><a href="/contact">Contact</a></li>
                  <li><a href="/privacy-policy">Privacy Policy</a></li>
                  <li><a href="/terms-conditions">Terms Conditions</a></li>
               </ul>
            </div>

            <div class="col-lg-2 col-md-3 col-6 mb-4">
               <h6 class="mb-4">Social Links</h6>
               <ul class="list-unstyled footer-list">
                  <li><a href="#">facebook</a></li>
                  <li><a href="#">twitter</a></li>
                  <li><a href="#">linkedin</a></li>
                  <li><a href="#">github</a></li>
               </ul>
            </div>

            <div class="col-md-3 mb-4">
               <h6 class="mb-4">Subscribe Newsletter</h6>
               <form class="subscription" action="javascript:void(0)" method="post">
                  <div class="position-relative">
                     <i class="ti-email email-icon"></i>
                     <input type="email" class="form-control" placeholder="Your Email Address">
                  </div>
                  <button class="btn btn-primary btn-block rounded" type="submit">Subscribe now</button>
               </form>
            </div>
         </div>
         <div class="scroll-top">
            <a href="javascript:void(0);" id="scrollTop"><i class="ti-angle-up"></i></a>
         </div>
         <div class="text-center">
            <p class="content">&copy; 2020 - Design &amp; Develop By <a href="https://astrum.uz/" target="_blank">Astrum</a></p>
         </div>
      </div>
   </footer>
   <!-- JS Plugins -->
   <script src="{% static 'plugins/jQuery/jquery.min.js' %}"></script>
   <script src="{% static 'plugins/bootstrap/bootstrap.min.js' %}" async></script>
   <script src="{% static 'plugins/slick/slick.min.js' %}"></script>

   <!-- Main Script -->
   <script src="{% static 'js/script.js' %}"></script>
</body>
</html>

templates/contact.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<section class="section-sm">
	<div class="container">
		<div class="row">
			<div class="col-12">
				<div class="title-bordered mb-5 d-flex align-items-center">
					<h1 class="h4">Talk To Me Anytime :)</h1>
					<ul class="list-inline social-icons ml-auto mr-3 d-none d-sm-block">
						<li class="list-inline-item"><a href="#"><i class="ti-facebook"></i></a>
						</li>
						<li class="list-inline-item"><a href="#"><i class="ti-twitter-alt"></i></a>
						</li>
						<li class="list-inline-item"><a href="#"><i class="ti-linkedin"></i></a>
						</li>
						<li class="list-inline-item"><a href="#"><i class="ti-github"></i></a>
						</li>
					</ul>
				</div>
			</div>
			<div class="col-md-6">
				<div class="content mb-5">
					<h1 id="ask-us-anything-br-or-just-say-hi">Ask Us Anything <br> Or just Say Hi,</h1>
					<p>Rather than just filling out a form, Sleeknote also offers help to the user
						<br>with links directing them to find additional information or take popular actions.</p>
					<h4 class="mt-5">Hate Forms? Write Us Email</h4>
					<p><i class="ti-email mr-2 text-primary"></i><a href="mailto:georgia.young@example.com">georgia.young@example.com</a>
					</p>
				</div>
			</div>
			<div class="col-md-6">
				<form method="POST" action="#">
					<div class="form-group">
						<label for="name">Your Name (Required)</label>
						<input type="text" name="name" id="name" class="form-control" required>
					</div>
					<div class="form-group">
						<label for="email">Your Email Address (Required)</label>
						<input type="email" name="email" id="email" class="form-control" required>
					</div>
					<div class="form-group">
						<label for="message">Your Message Here</label>
						<textarea name="message" id="message" class="form-control"></textarea>
					</div>
					<button type="submit" class="btn btn-primary">Send Now</button>
				</form>
			</div>
		</div>
	</div>
</section>


{% endblock  %}

templates/index.html
{% extends "base.html" %}
{% block content %}
{% load static %}
{% load blog_tags %}

<!-- navigation -->



<section class="section">
	<div class="container">
		<div class="row">
			<div class="col-lg-8  mb-5 mb-lg-0">

               {% for post in posts %}

                 {% if post.images.exists %}
				    <article class="row mb-5">
					<div class="col-md-4 mb-4 mb-md-0">
						<div class="post-slider slider-sm">
                             {% for image in post.images.all %}
                                <img loading="lazy" src="{{ image.image.url }}" class="img-fluid" alt="post-thumb" style="height:200px; object-fit: cover;">
                             {% endfor %}
						</div>
					</div>
					<div class="col-md-8">
						<h3 class="h5"><a class="post-title" href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
						<ul class="list-inline post-meta mb-2">
							<li class="list-inline-item"><i class="ti-user mr-2"></i><a href="author.html">{{ post.user }}</a>
							</li>
							<li class="list-inline-item">Date : {{ post.publish }}</li>
							<li class="list-inline-item">Categories :
                                {% for category in post.category.all %}
                                    <a href="{% url 'exam:post_by_category' category_id=category.id %}" class="ml-1">{{ category.name }}</a>
                                    {% if not forloop.last %}, {% endif %}
                                {% endfor %}
							</li>
							<li class="list-inline-item">Tags :
                                {% for tag in post.tags.all %}
                                <a href="{% url 'exam:post_list_by_tag' tag.slug %}" class="ml-1">{{ tag.name }} </a> {% if not forloop.last %}, {% endif %}
                                {% endfor %}
							</li>
						</ul>
						<p>{{ post.body|markdown|truncatewords:30|linebreaks }}</p> <a href="{{ post.get_absolute_url }}" class="btn btn-outline-primary">Continue Reading</a>
					</div>
				</article>

                {% else %}

                    <article class="row mb-5">
					<div class="col-12">
						<h3 class="h5"><a class="post-title" href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
						<ul class="list-inline post-meta mb-2">
							<li class="list-inline-item"><i class="ti-user mr-2"></i><a href="author.html">{{ post.user }}</a>
							</li>
							<li class="list-inline-item">Date : {{ post.publish }}</li>
							<li class="list-inline-item">Categories :
                                {% for category in post.category.all %}
                                    <a href="{% url 'exam:post_by_category' category_id=category.id %}" class="ml-1">{{ category.name }}</a>
                                    {% if not forloop.last %}, {% endif %}
                                {% endfor %}
							</li>
							<li class="list-inline-item">Tags :
                                {% for tag in post.tags.all %}
                                <a href="{% url 'exam:post_list_by_tag' tag.slug %}" class="ml-1">{{ tag.name }} </a> {% if not forloop.last %}, {% endif %}
                                {% endfor %}
							</li>
						</ul>
						<p>{{ post.body|markdown|truncatewords:30|linebreaks }}</p> <a href="{{ post.get_absolute_url }}" class="btn btn-outline-primary">Continue Reading</a>
					</div>
				</article>
            {% endif %}
                {% endfor %}

            <!-- Pagination -->
           <nav aria-label="Page navigation example">
            <ul class="pagination">
            {% if posts.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page=1" aria-label="First">
                    <span aria-hidden="true">&laquo;&laquo;</span>
                    <span class="sr-only">First</span>
            </a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ posts.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
            </a>
        </li>
        {% endif %}

        {% for i in posts.paginator.page_range %}
        {% if posts.number == i %}
        <li class="page-item active"><span class="page-link">{{ i }}</span></li>
        {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
        {% endfor %}

        {% if posts.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ posts.next_page_number }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
            </a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ posts.paginator.num_pages }}" aria-label="Last">
                <span aria-hidden="true">&raquo;&raquo;</span>
                <span class="sr-only">Last</span>
            </a>
        </li>
        {% endif %}
    </ul>
</nav>
             <!-- End Pagination -->
			</div>

       <!-- Sidebar -->
       <aside class="col-lg-4">
   <!-- Search -->
   <div class="widget">
      <h5 class="widget-title"><span>Search</span></h5>

      <form action="{% url 'exam:post_search' %}" method="get" class="widget-search">
         <input id="search-query" name="query" type="search" placeholder="Type &amp; Hit Enter...">
         <button type="submit"><i class="ti-search"></i>
         </button>
      </form>
   </div>

   <!-- categories -->


          <div class="widget">
    <h5 class="widget-title"><span>Categories</span></h5>
    <ul class="list-unstyled widget-list">
 {% for category in categories %}
                        <li>
                            <a href="{% url 'exam:post_by_category' category_id=category.id %}" class="d-flex">
                                {{ category.name }}
                                <small class="ml-auto">({{ category.posts.count }})</small>
                            </a>
                        </li>
                        {% endfor %}
    </ul>
</div>

   <!-- tags -->
   <div class="widget">
    <h5 class="widget-title"><span>Tags</span></h5>
    <ul class="list-inline widget-list-inline">
        {% for tag in unique_tags %}
        <li class="list-inline-item"><a href="{% url 'exam:post_list_by_tag' tag.slug %}">{{ tag.name }} </a></li>
        {% endfor %}
    </ul>
</div>


   <!-- latest post -->
   <div class="widget">
      <h5 class="widget-title"><span>Latest Article</span></h5>
       {% show_latest_posts 2 %}
   </div>
   </aside>


   <!-- End Sidebar -->
   </div>
</div>
</section>



{% endblock %}

templates/latest_posts.html
{% load blog_tags %}

    {% for post in latest_posts %}

      <ul class="list-unstyled widget-list">
         <li class="media widget-post align-items-center">
            <a href="{{ post.get_absolute_url }}">
                {% if post.images.all %}
                {% with post.images.all|first as first_image %}
                    <img loading="lazy" src="{{ first_image.image.url }}" class="mr-3" alt="post-thumb" >
                {% endwith %}
            {% endif %}
            </a>
            <div class="media-body">
               <h5 class="h6 mb-0"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h5>
               <small>{{ post.publish }}</small>
            </div>
         </li>
      </ul>
    {% endfor %}


templates/list.html
{% extends "base.html" %}
{% block content %}
{% load blog_tags %}
<section class="section">
	<div class="container">
		<h1 class="custom-heading mb-4">
            {% if query %}
                Posts containing "{{ query }}"
            {% elif tag %}
                Posts tagged with "{{ tag.name }}"
            {% elif category %}
                Posts in category "{{ category.name }}"
            {% else %}
                All Posts
            {% endif %}
        </h1>
		<div class="row">
			<div class="col-12  mb-5 mb-lg-0">
               {% for post in posts %}
                {% if post.images.exists %}

				<article class="row mb-5">
					<div class="col-md-4 mb-4 mb-md-0">
						<div class="post-slider slider-sm">
							{% for image in post.images.all %}
                                <img loading="lazy" src="{{ image.image.url }}" class="img-fluid" alt="post-thumb" style="height:200px; object-fit: cover;">
                             {% endfor %}
						</div>
					</div>
					<div class="col-md-8">
						<h3 class="h5"><a class="post-title" href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
						<ul class="list-inline post-meta mb-2">
							<li class="list-inline-item"><i class="ti-user mr-2"></i><a href="author.html">{{ post.user }}</a>
							</li>
							<li class="list-inline-item">Date : {{ post.publish }}</li>
							{% for category in post.category.all %}
                                    <a href="{% url 'exam:post_by_category' category_id=category.id %}" class="ml-1">{{ category.name }}</a>
                                    {% if not forloop.last %}, {% endif %}
                                {% endfor %}
							<li class="list-inline-item">Tags : {% for tag in post.tags.all %}
                                <a href="#" class="ml-1">{{ tag.name }} </a> {% if not forloop.last %}, {% endif %}
                                {% endfor %}
							</li>
						</ul>

						<p>{{ post.body|markdown|truncatewords:20|linebreaks }}</p> <a href="{{ post.get_absolute_url }}" class="btn btn-outline-primary">Continue Reading</a>

					</div>
				</article>
                {% else %}
				<article class="row mb-5">
					<div class="col-12">
						<h3 class="h5"><a class="post-title" href="post-details-2.html">{{ post.title }}</a></h3>
						<ul class="list-inline post-meta mb-2">
							<li class="list-inline-item"><i class="ti-user mr-2"></i><a href="author.html">{{ post.user }}</a>
							</li>
							<li class="list-inline-item">Date : {{ post.publish }}</li>
							<li class="list-inline-item">Categories :
                                {% for category in post.category.all %}
                                    <a href="{% url 'exam:post_by_category' category_id=category.id %}" class="ml-1">{{ category.name }}</a>
                                    {% if not forloop.last %}, {% endif %}
                                {% endfor %}
                            </li>
							<li class="list-inline-item">Tags :
                                {% for tag in post.tags.all %}
                                    <a href="#" class="ml-1">{{ tag.name }}</a>
                                    {% if not forloop.last %}, {% endif %}
                                {% endfor %}
                            </li>
						</ul>
						<p>{{ post.body|markdown|truncatewords:20|linebreaks }}</p> <a href="{{ post.get_absolute_url }}" class="btn btn-outline-primary">Continue Reading</a>
					</div>
				</article>

                    {% endif %}
				    {% endfor %}

                {% if results %}
                {% for post in results %}
                    {% if post.images.exists %}
                        <article class="row mb-5">
                            <div class="col-md-4 mb-4 mb-md-0">
                                <div class="post-slider slider-sm">
                                    {% for image in post.images.all %}
                                        <img loading="lazy" src="{{ image.image.url }}" class="img-fluid" alt="post-thumb" style="height:200px; object-fit: cover;">
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="col-md-8">
                                <h3 class="h5"><a class="post-title" href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
                                <ul class="list-inline post-meta mb-2">
                                    <li class="list-inline-item"><i class="ti-user mr-2"></i><a href="author.html">{{ post.user }}</a></li>
                                    <li class="list-inline-item">Date : {{ post.publish }}</li>
                                    {% for category in post.category.all %}
                                        <a href="{% url 'exam:post_by_category' category_id=category.id %}" class="ml-1">{{ category.name }}</a>
                                        {% if not forloop.last %}, {% endif %}
                                    {% endfor %}
                                    <li class="list-inline-item">Tags :
                                        {% for tag in post.tags.all %}
                                            <a href="#" class="ml-1">{{ tag.name }}</a>
                                            {% if not forloop.last %}, {% endif %}
                                        {% endfor %}
                                    </li>
                                </ul>
                                <p>{{ post.body|markdown|truncatewords:20|linebreaks }}</p>
                                <a href="{{ post.get_absolute_url }}" class="btn btn-outline-primary">Continue Reading</a>
                            </div>
                        </article>
                    {% else %}
                        <article class="row mb-5">
                            <div class="col-12">
                                <h3 class="h5"><a class="post-title" href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
                                <ul class="list-inline post-meta mb-2">
                                    <li class="list-inline-item"><i class="ti-user mr-2"></i><a href="author.html">{{ post.user }}</a></li>
                                    <li class="list-inline-item">Date : {{ post.publish }}</li>
                                    <li class="list-inline-item">Categories :
                                        {% for category in post.category.all %}
                                            <a href="{% url 'exam:post_by_category' category_id=category.id %}" class="ml-1">{{ category.name }}</a>
                                            {% if not forloop.last %}, {% endif %}
                                        {% endfor %}
                                    </li>
                                    <li class="list-inline-item">Tags :
                                        {% for tag in post.tags.all %}
                                            <a href="#" class="ml-1">{{ tag.name }}</a>
                                            {% if not forloop.last %}, {% endif %}
                                        {% endfor %}
                                    </li>
                                </ul>
                                <p>{{ post.body|markdown|truncatewords:20|linebreaks }}</p>
                                <a href="{{ post.get_absolute_url }}" class="btn btn-outline-primary">Continue Reading</a>
                            </div>
                        </article>
                    {% endif %}
                {% endfor %}
            {% else %}
                <p>No posts found for "{{ query }}"</p>
            {% endif %}


                <!-- Pagination -->
                <nav aria-label="Page navigation example">
    <ul class="pagination">
        {% if posts.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page=1" aria-label="First">
                <span aria-hidden="true">&laquo;&laquo;</span>
                <span class="sr-only">First</span>
            </a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ posts.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
            </a>
        </li>
        {% endif %}


        {% for i in posts.paginator.page_range %}
        {% if posts.number == i %}
            <li class="page-item active"><span class="page-link">{{ i }}</span></li>
        {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
        {% endfor %}

        {% if posts.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ posts.next_page_number }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
            </a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ posts.paginator.num_pages }}" aria-label="Last">
                <span aria-hidden="true">&raquo;&raquo;</span>
                <span class="sr-only">Last</span>
            </a>
        </li>
        {% endif %}
    </ul>
</nav>
					<!-- End Pagination -->
			</div>
		</div>
	</div>
</section>


    {% endblock %}

templates/search.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}Search{% endblock %}
{% block content %}
    {% if query %}
<h1 xmlns:exam="http://www.w3.org/1999/xhtml">Posts containing "{{ query }}"</h1>
        <h3>
            {% with results.count as total_results %}
                Found {{ total_results }} result{{ total_results|pluralize }}
            {% endwith %}
        </h3>
        {% for post in results %}
            <h4>
                <a href="{{ post.get_absolute_url }}">
                    {{ post.title }}
                </a>
            </h4>
            {{ post.body|markdown|truncatewords_html:12 }}
        {% empty %}
            <p>There are no results for your query.</p>
        {% endfor %}
        <p><a href="{% url "exam:post_search" %}">Search again</a></p>
    {% else %}
        <h1>Search for posts</h1>
        <form method="get">
            {{ form.as_p }}
            <input type="submit" value="Search">
        </form>
    {% endif %}
{% endblock %}